#+STARTUP: hidestars
#+TODO: TODO IN_PROGRESS | DONE

* Summary
  In honor of my grandfather whose mind was so emcompassing
  that it left its shell long before his body realized.

* WebGL

** [2018-01-25 Thu]
   .o0(i really need to remember to write my journey through
   this project down each day...)

   i got to a point where i can draw a rectangle but not
   without problems. i'm only sending 2 components, x and y,
   in the buffer, just like in the demo but somehow the
   latter works with a =vec4= position attribute but not
   mine; i have to make it a =vec2= and fill it up to a
   =vec4=. So far, this is a mystery but i need to move on,
   and history tells me that i will figure it out someday.

   i need to move =gl= functions into its own
   library. keeping the context in =Canvas= is more
   typing... 

   then add a rotation to the rectangle.

** [2017-12-27 Wed]
   i got the canvas almost set up. programs go in there
   rather fitly, but wondering about buffers and/or
   variables. in nullprogram's sample code, the variables
   are attached at render, and, in learningwebgl, they are
   attached during program inititialization and in render.

** [2017-12-25 Mon]
   looks like there will be many programs for each thing i
   want to draw. 
   
   WebGL pipeline (high-level):
   1. Runs the vertex shader on all of the vertices to work
      out where everything is.
   2. Linearly interpolates between the vertices, which
      tells it which fragments (which for the moment you can
      treat as being the same as pixels) need to be painted.
   3. For each fragment, run the fragment shader on it to
      work out its colour.
   4. Write it to the frame buffer.

*** Variable types
    - [[https://webglfundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html#attributes][attributes]] :: data pulled from buffers
    - [[https://webglfundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html#uniforms][uniforms]] :: values that stay the same during for all
         vertices of a single draw call

** Topics

*** [[https://webglfundamentals.org/webgl/lessons/webgl-drawing-multiple-things.html][Drawing multiple things]]
    For each thing you want to draw
    - call =gl.useProgram= for the program needed to draw.
    - setup attributes for the thing you want to draw for
      each attribute call =gl.bindBuffer=,
      =gl.vertexAttribPointer=, =gl.enableVertexAttribArray=
    - setup uniforms for the thing you want to draw
    - call =gl.uniformXXX= for each uniform
    - call =gl.activeTexture= and =gl.bindTexture= to assign
      textures to texture units.
    - call =gl.drawArrays= or =gl.drawElements=

*** Perspective/Projection Matrix
    - fov :: 45° field of view
    - f :: inverse tangent of 22.5°
* Refs
  - http://nullprogram.com/sphere-js/
  - [[http://learningwebgl.com/blog/?p=859][learningwebgl: blending]]

** Webserver
   Start a webserver to serve the shader files, just for
   better legibility.

   #+BEGIN_SRC lisp
     (ql:quickload :hunchentoot)
     (hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 4242))
     (push (hunchentoot:create-folder-dispatcher-and-handler
            "/nvm/" "~/work/gamedev/passed-in-future/nvm/")
           hunchentoot:*dispatch-table*)
   #+END_SRC

   then visit http://localhost:4242/nvm/index.html.

* Tasks

** IN_PROGRESS learn some WebGL
   Start with rotating colorful rectangles.

